
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import Jama.*;
import java.util.Arrays;

import java.util.LinkedHashMap;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/*
 * PR_GUI.java
 *
 * Created on 2016-10-19, 19:40:56
 */


/**
 *
 * @author DSJ
 */

public class PR_GUI extends javax.swing.JFrame {

    String InData; // dataset from a text file will be placed here
    int ClassCount=0, FeatureCount=0;
    double[][] F, FNew; // original feature matrix and reduced feature matrix FNew
    int[] ClassLabels, SampleCount;
    String[] ClassNames;
    ArrayList selboxItems = new ArrayList<String>();
    boolean isRead = false, isTrained=false, isParsed = false;
    private Fisher fisher;
    
    
    /** Creates new form PR_GUI */
    public PR_GUI() {
        
        selboxItems.add(Integer.toString(1));

        initComponents();
        selbox_nfeat1.setSelectedItem(1);
        selbox_nfeat1.setEnabled(false);
        selbox_kSamples.setSelectedItem(1);
        selbox_kSamples.setEnabled(false);
        setSize(720,410);
        printAreaClassifier.setEditable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbg_F = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        b_read = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_dataset_name_l = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_dataset_name = new javax.swing.JLabel();
        l_nfeatures = new javax.swing.JLabel();
        classCount = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        f_rb_extr = new javax.swing.JRadioButton();
        f_rb_sel = new javax.swing.JRadioButton();
        b_deriveFS = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        f_combo_criterion = new javax.swing.JComboBox();
        f_combo_PCA_LDA = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        tf_PCA_Energy = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        l_NewDim = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selbox_nfeat1 = new javax.swing.JComboBox();
        FSalgorithm = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        selectClassMeth = new javax.swing.JComboBox();
        b_Train = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tf_TrainSetSize = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        classifClasses = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        classifierAccur = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        selbox_kSamples = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jScrollPaneClassifier = new javax.swing.JScrollPane();
        printAreaClassifier = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        l_FLD_val = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b_read.setText("Read dataset");
        b_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_readActionPerformed(evt);
            }
        });
        getContentPane().add(b_read);
        b_read.setBounds(20, 10, 130, 23);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Dataset info");

        l_dataset_name_l.setText("Name:");

        jLabel3.setText("Classes:");

        jLabel4.setText("Features:");

        l_dataset_name.setText("...");

        l_nfeatures.setText("...");

        classCount.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l_dataset_name_l)
                        .addGap(18, 18, 18)
                        .addComponent(l_dataset_name))
                    .addComponent(jLabel1))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classCount)
                    .addComponent(l_nfeatures))
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(classCount))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_dataset_name_l)
                    .addComponent(jLabel4)
                    .addComponent(l_dataset_name)
                    .addComponent(l_nfeatures))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 50, 320, 80);

        jButton2.setText("Parse dataset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 10, 130, 23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Feature space");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(14, 2, 118, 26);

        jLabel6.setText("FS Dimension");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(178, 9, 63, 14);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(10, 80, 290, 10);

        f_rb_extr.setBackground(new java.awt.Color(255, 255, 204));
        rbg_F.add(f_rb_extr);
        f_rb_extr.setText("Feature extraction");
        f_rb_extr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_rb_extrActionPerformed(evt);
            }
        });
        jPanel3.add(f_rb_extr);
        f_rb_extr.setBounds(20, 140, 115, 23);

        f_rb_sel.setBackground(new java.awt.Color(255, 255, 204));
        rbg_F.add(f_rb_sel);
        f_rb_sel.setSelected(true);
        f_rb_sel.setText("Feature selection");
        f_rb_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_rb_selActionPerformed(evt);
            }
        });
        jPanel3.add(f_rb_sel);
        f_rb_sel.setBounds(10, 110, 109, 23);

        b_deriveFS.setText("Derive Feature Space");
        b_deriveFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deriveFSActionPerformed(evt);
            }
        });
        jPanel3.add(b_deriveFS);
        b_deriveFS.setBounds(10, 200, 292, 23);

        jLabel10.setText("Criterion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(210, 90, 41, 14);

        f_combo_criterion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fisher discriminant", "Classification error" }));
        f_combo_criterion.setEnabled(false);
        jPanel3.add(f_combo_criterion);
        f_combo_criterion.setBounds(160, 110, 140, 20);

        f_combo_PCA_LDA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PCA", "LDA" }));
        f_combo_PCA_LDA.setEnabled(false);
        jPanel3.add(f_combo_PCA_LDA);
        f_combo_PCA_LDA.setBounds(190, 140, 70, 20);

        jLabel12.setText("Energy");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 170, 34, 14);

        tf_PCA_Energy.setText("80");
        tf_PCA_Energy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_PCA_EnergyActionPerformed(evt);
            }
        });
        jPanel3.add(tf_PCA_Energy);
        tf_PCA_Energy.setBounds(70, 170, 30, 20);

        jLabel14.setText("%");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(110, 170, 20, 14);

        jLabel15.setText("New dimension:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(160, 170, 75, 14);

        l_NewDim.setText("...");
        jPanel3.add(l_NewDim);
        l_NewDim.setBounds(270, 170, 30, 14);

        jLabel7.setText("FS Algorithm");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 50, 70, 14);

        selbox_nfeat1.setModel(new DefaultComboBoxModel(selboxItems.toArray()));
        selbox_nfeat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selbox_nfeat1ActionPerformed(evt);
            }
        });
        jPanel3.add(selbox_nfeat1);
        selbox_nfeat1.setBounds(258, 6, 50, 20);

        FSalgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SFS", "BruteForce" }));
        FSalgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FSalgorithmActionPerformed(evt);
            }
        });
        jPanel3.add(FSalgorithm);
        FSalgorithm.setBounds(170, 50, 78, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 140, 320, 240);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setText("Classifier");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 0, 79, 26);

        jLabel9.setText("Method");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(14, 44, 50, 14);

        selectClassMeth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nearest neighbor (NN)", "Nearest Mean (NM)", "k-Nearest Neighbor (k-NN)", "k-Nearest Mean (k-NM)" }));
        selectClassMeth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectClassMethItemStateChanged(evt);
            }
        });
        selectClassMeth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClassMethActionPerformed(evt);
            }
        });
        jPanel4.add(selectClassMeth);
        selectClassMeth.setBounds(74, 41, 152, 20);

        b_Train.setText("Train");
        b_Train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TrainActionPerformed(evt);
            }
        });
        jPanel4.add(b_Train);
        b_Train.setBounds(40, 100, 98, 20);

        jButton4.setText("Execute");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(210, 100, 96, 23);

        jLabel16.setText("Training part:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 130, 80, 14);

        tf_TrainSetSize.setText("80");
        tf_TrainSetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TrainSetSizeActionPerformed(evt);
            }
        });
        jPanel4.add(tf_TrainSetSize);
        tf_TrainSetSize.setBounds(90, 130, 20, 20);

        jLabel17.setText("%");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(120, 130, 20, 14);

        jLabel11.setText("Classified classes (testSample):");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 160, 190, 14);

        classifClasses.setText("\"");
        jPanel4.add(classifClasses);
        classifClasses.setBounds(210, 160, 130, 30);

        jLabel19.setText("Accuracy of classification:");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 190, 170, 14);

        classifierAccur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        classifierAccur.setText("0");
        jPanel4.add(classifierAccur);
        classifierAccur.setBounds(210, 190, 30, 14);

        jLabel21.setText("%");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(240, 190, 20, 14);

        selbox_kSamples.setModel(new DefaultComboBoxModel(selboxItems.toArray()));
        selbox_kSamples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selbox_kSamplesActionPerformed(evt);
            }
        });
        jPanel4.add(selbox_kSamples);
        selbox_kSamples.setBounds(170, 70, 50, 20);

        jLabel18.setText("Number of samples (k)");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 70, 140, 14);

        printAreaClassifier.setColumns(20);
        printAreaClassifier.setRows(5);
        jScrollPaneClassifier.setViewportView(printAreaClassifier);

        jPanel4.add(jScrollPaneClassifier);
        jScrollPaneClassifier.setBounds(230, 20, 106, 66);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(340, 150, 350, 230);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));
        jPanel5.setLayout(null);

        jLabel2.setText("FS Winner:");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 30, 70, 14);

        jLabel13.setText("FLD value: ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 100, 70, 14);

        l_FLD_val.setText("vvv");
        jPanel5.add(l_FLD_val);
        l_FLD_val.setBounds(100, 100, 70, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(90, 20, 250, 80);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(340, 10, 350, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_rb_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_rb_selActionPerformed
        f_combo_criterion.setEnabled(true);
        f_combo_PCA_LDA.setEnabled(false);
    }//GEN-LAST:event_f_rb_selActionPerformed

    private void f_rb_extrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_rb_extrActionPerformed
        f_combo_criterion.setEnabled(false);
        f_combo_PCA_LDA.setEnabled(true);
    }//GEN-LAST:event_f_rb_extrActionPerformed

    private void b_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_readActionPerformed
        // reads in a text file; contents is placed into a variable of String type
        InData = readDataSet();
        if (!InData.equals(""))isRead=true;
    }//GEN-LAST:event_b_readActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Analyze text inputted from a file: determine class number and labels and number
        // of features; build feature matrix: columns - samples, rows - features
        try {
            if(InData!=null) {
                getDatasetParameters();
                l_nfeatures.setText(FeatureCount+"");
                
                fillFeatureMatrix();
                isParsed=true;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        classifClasses.setText("'");
        selbox_nfeat1.setEnabled(true);
        initializeSelboxItems();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b_deriveFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deriveFSActionPerformed
        // derive optimal feature space
        if(F==null) return;
        if(f_rb_sel.isSelected()){
            // the chosen strategy is feature selection
            int[] flags = new int[FeatureCount];
            fisher = new Fisher(this);
        }
        else if(f_rb_extr.isSelected()){
          FeatureExtraction featureEx = new FeatureExtraction(this);
            
        }
    }//GEN-LAST:event_b_deriveFSActionPerformed

    private void b_TrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TrainActionPerformed
        
        // first step: split dataset (in new feature space) into training / testing parts
        if(isRead && isParsed){
            dataTrainer DT = new dataTrainer(this,1);
            
            if(FNew==null){     // if no reduced feature space have been derived
                DT.generateTraining_and_Test_Flags(F, tf_TrainSetSize.getText());
            }   else{
               DT.generateTraining_and_Test_Flags(FNew, tf_TrainSetSize.getText()); 
            }
            isTrained=true;
        }else if(!isRead){
            printAreaClassifier.setText ("You need to read data set first!");
        }else if(!isParsed){
            printAreaClassifier.setText ("You need to parse data set first!");
        }
        
        

    }//GEN-LAST:event_b_TrainActionPerformed

    private void tf_PCA_EnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_PCA_EnergyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_PCA_EnergyActionPerformed

    private void selbox_nfeat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selbox_nfeat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selbox_nfeat1ActionPerformed

    private void FSalgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FSalgorithmActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_FSalgorithmActionPerformed

    private void tf_TrainSetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TrainSetSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TrainSetSizeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if ( selectClassMeth.getSelectedItem().equals("k-Nearest Mean (k-NM)")){
           System.out.println("done perfectly");
        }
        if(isTrained){
           if ( selectClassMeth.getSelectedItem().equals("Nearest neighbor (NN)")){
                NNClassifier CNN = new NNClassifier(this);
                CNN.classifySamples();
            } else if(selectClassMeth.getSelectedItem().equals("Nearest Mean (NM)")){
                NMClassifier CNM = new NMClassifier(this);
                CNM.classifySamples();
            }else if(selectClassMeth.getSelectedItem().equals("k-Nearest Neighbor (k-NN)")){
                System.out.println("done even better"); //dodać implementację
            }else if(selectClassMeth.getSelectedItem().equals("k-Nearest Mean (k-NM)")){
                System.out.println("done perfectly"); //dodać implementację
            }
        
        } else printAreaClassifier.setText ("You need to train Classifier first!");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void selectClassMethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClassMethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectClassMethActionPerformed

    private void selbox_kSamplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selbox_kSamplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selbox_kSamplesActionPerformed

    private void selectClassMethItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectClassMethItemStateChanged
        if(selectClassMeth.getSelectedItem().equals("k-Nearest Mean (k-NM)") ||
                selectClassMeth.getSelectedItem().equals("k-Nearest Neighbor (k-NN)")){
            selbox_kSamples.setEnabled(true);
        } else if(selectClassMeth.getSelectedItem().equals("Nearest neighbor(NN)") ||
                selectClassMeth.getSelectedItem().equals("Nearest Mean (NM)")){
            selbox_kSamples.setEnabled(false);
        }
    }//GEN-LAST:event_selectClassMethItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PR_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FSalgorithm;
    private javax.swing.JButton b_Train;
    private javax.swing.JButton b_deriveFS;
    private javax.swing.JButton b_read;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel classCount;
    private javax.swing.JLabel classifClasses;
    private javax.swing.JLabel classifierAccur;
    private javax.swing.JComboBox f_combo_PCA_LDA;
    private javax.swing.JComboBox f_combo_criterion;
    private javax.swing.JRadioButton f_rb_extr;
    private javax.swing.JRadioButton f_rb_sel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneClassifier;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel l_FLD_val;
    protected javax.swing.JLabel l_NewDim;
    private javax.swing.JLabel l_dataset_name;
    private javax.swing.JLabel l_dataset_name_l;
    private javax.swing.JLabel l_nfeatures;
    private javax.swing.JTextArea printAreaClassifier;
    private javax.swing.ButtonGroup rbg_F;
    private javax.swing.JComboBox selbox_kSamples;
    private javax.swing.JComboBox selbox_nfeat1;
    private javax.swing.JComboBox selectClassMeth;
    private javax.swing.JTextField tf_PCA_Energy;
    private javax.swing.JTextField tf_TrainSetSize;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return 
     */
    private String readDataSet() {

        String s_tmp, s_out="";
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File(".."));
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                                            "Datasets - plain text files", "txt");
        jfc.setFileFilter(filter);
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedReader br = new BufferedReader(new FileReader(jfc.getSelectedFile()));
                while((s_tmp=br.readLine())!=null) s_out += s_tmp + '$';
                br.close();
                l_dataset_name.setText(jfc.getSelectedFile().getName());
            } catch (Exception e) {        }
        }
        return s_out;
    }

    /**
     * 
     * @throws Exception 
     */
    private void getDatasetParameters() throws Exception{
        // based on data stored in InData determine: class count and names, number of samples 
        // and number of features; set the corresponding variables
        String stmp=InData, saux="";
        // analyze the first line and get feature count: assume that number of features
        // equals number of commas
        saux = InData.substring(InData.indexOf(',')+1, InData.indexOf('$'));
        if(saux.length()==0) throw new Exception("The first line is empty");
        // saux stores the first line beginning from the first comma
        int count=0;
        while(saux.indexOf(',') >0){
            saux = saux.substring(saux.indexOf(',')+1);            
            count++;
        }
        FeatureCount = count+1; // the first parameter
        // Determine number of classes, class names and number of samples per class
        boolean New;
        int index=-1;
        List<String> NameList = new ArrayList<String>();
        List<Integer> CountList = new ArrayList<Integer>();
        List<Integer> LabelList = new ArrayList<Integer>();
        while(stmp.length()>1){
            saux = stmp.substring(0,stmp.indexOf(' '));
            New = true; 
            index++; // new class index
            for(int i=0; i<NameList.size();i++) 
                if(saux.equals(NameList.get(i))) {
                    New=false;
                    index = i; // class index
                }
            if(New) {
                NameList.add(saux);
                CountList.add(0);
            }
            else{
                CountList.set(index, CountList.get(index).intValue()+1);
            }           
            LabelList.add(index); // class index for current row
            stmp = stmp.substring(stmp.indexOf('$')+1);
        }
        // based on results of the above analysis, create variables
        ClassNames = new String[NameList.size()];
        for(int i=0; i<ClassNames.length; i++)
            ClassNames[i]=NameList.get(i);
        SampleCount = new int[CountList.size()];
        for(int i=0; i<SampleCount.length; i++)
            SampleCount[i] = CountList.get(i).intValue()+1;
        ClassLabels = new int[LabelList.size()];
        for(int i=0; i<ClassLabels.length; i++)
            ClassLabels[i] = LabelList.get(i).intValue(); //sets the label for the class
    classCount.setText(Integer.toString(ClassCount = ClassNames.length));
    }

    /**
     * 
     * @throws Exception 
     */
    private void fillFeatureMatrix() throws Exception {
        // having determined array size and class labels, fills in the feature matrix
        int n = 0;
        String saux, stmp = InData;
        for(int i=0; i<SampleCount.length; i++)
            n += SampleCount[i];
        if(n<=0) throw new Exception("no samples found");
        F = new double[FeatureCount][n]; // samples are placed column-wise
        for(int j=0; j<n; j++){
            saux = stmp.substring(0,stmp.indexOf('$'));
            saux = saux.substring(stmp.indexOf(',')+1);
            for(int i=0; i<FeatureCount-1; i++) {
                F[i][j] = Double.parseDouble(saux.substring(0,saux.indexOf(',')));
                saux = saux.substring(saux.indexOf(',')+1);
            }
            F[FeatureCount-1][j] = Double.parseDouble(saux);
            stmp = stmp.substring(stmp.indexOf('$')+1);
        }
        int cc = 1;
    }
      public double[][] getF() {
      //System.out.println(F[1][1]); 
      return F;
  }
 
        public double[][] getFNew(){
      return FNew;
  }    
   public void setFNew(int f) {
      FeatureCount = f;
  }
        
        
  public int getFeatureCount() {
      return FeatureCount;
  }

 public void setFeatureCount(int f) {
      FeatureCount = f;
  }


public int[] getClassLabels() {
      return ClassLabels;
  }

public String gettf_PCA_Energy() {
      return tf_PCA_Energy.getText();
  }

public void setl_NewDim(String setter){
    l_NewDim.setText(setter);
}

public void setClassifyClasses(String setter){
    classifClasses.setText(setter);
}
public void addClassifyClasses(String setter){
    classifClasses.setText(classifClasses.getText()+setter);
}

public void addClassifyLine(String setter){
    printAreaClassifier.setText(printAreaClassifier.getText()+"\n"+setter);
    //printAreaClassifier.append("\n"+setter);
}
public void clearClassifier(){
    printAreaClassifier.setText("");
    classifClasses.setText("'");
    classifierAccur.setText("0");
}

public void setClassifierAcc(String setter){
    classifierAccur.setText(setter);
    System.out.println(setter);
}
public int getClassCount(){
    
    return Integer.parseInt(classCount.getText());
    }

public boolean getIsRead(){
    
    return isRead;
}

public boolean getIsParsed(){
    
    return isParsed;
    }
/**
 * 
 * @return sample count for all classes
 */
public int getSamplesCount(){
    
    return F[0].length;
    }


public int getKSamplesCount(){
    return Integer.parseInt(selbox_kSamples.getSelectedItem().toString());
}

private void initializeSelboxItems(){
    
    initializeOneSelboxItem((DefaultComboBoxModel)selbox_nfeat1.getModel(), getFeatureCount()-1); //selecting the same amount of features makes no sense
    initializeOneSelboxItem((DefaultComboBoxModel)selbox_kSamples.getModel(), getSamplesCount()/getClassCount());  
}

private void initializeOneSelboxItem(DefaultComboBoxModel JComboBox, int nSelection){
    DefaultComboBoxModel model = (DefaultComboBoxModel) JComboBox;
    model.removeAllElements();
    for (int i=1;i<=nSelection;i++){          
            model.addElement(Integer.toString(i));
        }
}

public javax.swing.JComboBox<String> getFSalgorithm() {
        return FSalgorithm;
    }

public javax.swing.JLabel getl_FLD_val() {
        return l_FLD_val;
    }
    
    public javax.swing.JTextArea getjTextArea1()
    {
        return  jTextArea1;
    }
    
      public int[] getSampleCount() {
        return SampleCount;
    }
      
    public javax.swing.JComboBox getSelbox_nfeat1() {
        return selbox_nfeat1;
    }

}